/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkbenchChatRouteImport } from './routes/api/workbench-chat'
import { Route as ApiWorkRouteImport } from './routes/api/work'
import { Route as ApiVibecodeRouteImport } from './routes/api/vibecode'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiSpeakRouteImport } from './routes/api/speak'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiExplainRouteImport } from './routes/api/explain'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWorkbenchRouteImport } from './routes/_authenticated/workbench'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedExplainRouteImport } from './routes/_authenticated/explain'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConnectorsRouteImport } from './routes/_authenticated/connectors'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as ApiPublicOauthProviderStartRouteImport } from './routes/api/public/oauth.$provider.start'
import { Route as ApiPublicOauthProviderCallbackRouteImport } from './routes/api/public/oauth.$provider.callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkbenchChatRoute = ApiWorkbenchChatRouteImport.update({
  id: '/api/workbench-chat',
  path: '/api/workbench-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkRoute = ApiWorkRouteImport.update({
  id: '/api/work',
  path: '/api/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVibecodeRoute = ApiVibecodeRouteImport.update({
  id: '/api/vibecode',
  path: '/api/vibecode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeakRoute = ApiSpeakRouteImport.update({
  id: '/api/speak',
  path: '/api/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainRoute = ApiExplainRouteImport.update({
  id: '/api/explain',
  path: '/api/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkbenchRoute = AuthenticatedWorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExplainRoute = AuthenticatedExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectorsRoute = AuthenticatedConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicOauthProviderStartRoute =
  ApiPublicOauthProviderStartRouteImport.update({
    id: '/api/public/oauth/$provider/start',
    path: '/api/public/oauth/$provider/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthProviderCallbackRoute =
  ApiPublicOauthProviderCallbackRouteImport.update({
    id: '/api/public/oauth/$provider/callback',
    path: '/api/public/oauth/$provider/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explain': typeof AuthenticatedExplainRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workbench': typeof AuthenticatedWorkbenchRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/news': typeof ApiNewsRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/vibecode': typeof ApiVibecodeRoute
  '/api/work': typeof ApiWorkRoute
  '/api/workbench-chat': typeof ApiWorkbenchChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/oauth/$provider/callback': typeof ApiPublicOauthProviderCallbackRoute
  '/api/public/oauth/$provider/start': typeof ApiPublicOauthProviderStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explain': typeof AuthenticatedExplainRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workbench': typeof AuthenticatedWorkbenchRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/news': typeof ApiNewsRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/vibecode': typeof ApiVibecodeRoute
  '/api/work': typeof ApiWorkRoute
  '/api/workbench-chat': typeof ApiWorkbenchChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/api/public/oauth/$provider/callback': typeof ApiPublicOauthProviderCallbackRoute
  '/api/public/oauth/$provider/start': typeof ApiPublicOauthProviderStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/connectors': typeof AuthenticatedConnectorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/explain': typeof AuthenticatedExplainRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workbench': typeof AuthenticatedWorkbenchRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/news': typeof ApiNewsRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/vibecode': typeof ApiVibecodeRoute
  '/api/work': typeof ApiWorkRoute
  '/api/workbench-chat': typeof ApiWorkbenchChatRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/oauth/$provider/callback': typeof ApiPublicOauthProviderCallbackRoute
  '/api/public/oauth/$provider/start': typeof ApiPublicOauthProviderStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/connectors'
    | '/dashboard'
    | '/explain'
    | '/settings'
    | '/workbench'
    | '/api/chat'
    | '/api/explain'
    | '/api/news'
    | '/api/speak'
    | '/api/transcribe'
    | '/api/vibecode'
    | '/api/work'
    | '/api/workbench-chat'
    | '/chat/$threadId'
    | '/chat/'
    | '/api/public/oauth/$provider/callback'
    | '/api/public/oauth/$provider/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/connectors'
    | '/dashboard'
    | '/explain'
    | '/settings'
    | '/workbench'
    | '/api/chat'
    | '/api/explain'
    | '/api/news'
    | '/api/speak'
    | '/api/transcribe'
    | '/api/vibecode'
    | '/api/work'
    | '/api/workbench-chat'
    | '/chat/$threadId'
    | '/chat'
    | '/api/public/oauth/$provider/callback'
    | '/api/public/oauth/$provider/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/connectors'
    | '/_authenticated/dashboard'
    | '/_authenticated/explain'
    | '/_authenticated/settings'
    | '/_authenticated/workbench'
    | '/api/chat'
    | '/api/explain'
    | '/api/news'
    | '/api/speak'
    | '/api/transcribe'
    | '/api/vibecode'
    | '/api/work'
    | '/api/workbench-chat'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/chat/'
    | '/api/public/oauth/$provider/callback'
    | '/api/public/oauth/$provider/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExplainRoute: typeof ApiExplainRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiSpeakRoute: typeof ApiSpeakRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiVibecodeRoute: typeof ApiVibecodeRoute
  ApiWorkRoute: typeof ApiWorkRoute
  ApiWorkbenchChatRoute: typeof ApiWorkbenchChatRoute
  ApiPublicOauthProviderCallbackRoute: typeof ApiPublicOauthProviderCallbackRoute
  ApiPublicOauthProviderStartRoute: typeof ApiPublicOauthProviderStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workbench-chat': {
      id: '/api/workbench-chat'
      path: '/api/workbench-chat'
      fullPath: '/api/workbench-chat'
      preLoaderRoute: typeof ApiWorkbenchChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/work': {
      id: '/api/work'
      path: '/api/work'
      fullPath: '/api/work'
      preLoaderRoute: typeof ApiWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vibecode': {
      id: '/api/vibecode'
      path: '/api/vibecode'
      fullPath: '/api/vibecode'
      preLoaderRoute: typeof ApiVibecodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speak': {
      id: '/api/speak'
      path: '/api/speak'
      fullPath: '/api/speak'
      preLoaderRoute: typeof ApiSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain': {
      id: '/api/explain'
      path: '/api/explain'
      fullPath: '/api/explain'
      preLoaderRoute: typeof ApiExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workbench': {
      id: '/_authenticated/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof AuthenticatedWorkbenchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explain': {
      id: '/_authenticated/explain'
      path: '/explain'
      fullPath: '/explain'
      preLoaderRoute: typeof AuthenticatedExplainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connectors': {
      id: '/_authenticated/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AuthenticatedConnectorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/oauth/$provider/start': {
      id: '/api/public/oauth/$provider/start'
      path: '/api/public/oauth/$provider/start'
      fullPath: '/api/public/oauth/$provider/start'
      preLoaderRoute: typeof ApiPublicOauthProviderStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/$provider/callback': {
      id: '/api/public/oauth/$provider/callback'
      path: '/api/public/oauth/$provider/callback'
      fullPath: '/api/public/oauth/$provider/callback'
      preLoaderRoute: typeof ApiPublicOauthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConnectorsRoute: typeof AuthenticatedConnectorsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExplainRoute: typeof AuthenticatedExplainRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkbenchRoute: typeof AuthenticatedWorkbenchRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConnectorsRoute: AuthenticatedConnectorsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExplainRoute: AuthenticatedExplainRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkbenchRoute: AuthenticatedWorkbenchRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExplainRoute: ApiExplainRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiSpeakRoute: ApiSpeakRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiVibecodeRoute: ApiVibecodeRoute,
  ApiWorkRoute: ApiWorkRoute,
  ApiWorkbenchChatRoute: ApiWorkbenchChatRoute,
  ApiPublicOauthProviderCallbackRoute: ApiPublicOauthProviderCallbackRoute,
  ApiPublicOauthProviderStartRoute: ApiPublicOauthProviderStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
